[workspace]
members = ["crates/*", "packages/create-farm", "rust-plugins/*"]
resolver = "2"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
strip = true
panic = "abort"

[profile.ci-test]
inherits = "release"
opt-level = 0
codegen-units = 256
incremental = true
lto = false
debug = true
