[package]
edition = "2021"
name = "farmfe_plugin_file_size"
version = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
farmfe_core = { version = "*", path = "../../crates/core" }
farmfe_macro_plugin = { version = "*", path = "../../crates/macro_plugin" }
farmfe_toolkit_plugin_types = { version = "*", path = "../../crates/toolkit_plugin_types" }
farmfe_toolkit = { version = "*", path = "../../crates/toolkit" }
flate2 = "1.0.35"
colored = "3.0.0"
unicode-width = "0.1.10"
