[package]
edition = "2021"
name = "create-farm-rs"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.16", default-features = false, features = ["napi4"] }
napi-derive = "2.16"
create-farm = { path = "../create-farm-rs" }

[build-dependencies]
napi-build = "2.1"
